//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LINQ_LandenStedenTalen_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class lst_Land
    {
        public lst_Land()
        {
            this.lst_Steden = new HashSet<lst_Stad>();
            this.lst_Talen = new HashSet<lst_Taal>();
        }
    
        public string LandCode { get; set; }
        public string Naam { get; set; }
    
        public virtual ICollection<lst_Stad> lst_Steden { get; set; }
        public virtual ICollection<lst_Taal> lst_Talen { get; set; }
    }
}
